version: 2.1

orbs:
  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

jobs:
  run-specs-with-mysql:
    executor:
      name: solidusio_extensions/mysql
      ruby_version: <<parameters.ruby_version>>
    steps:
      - checkout
      - solidusio_extensions/run-tests-solidus-older
      - solidusio_extensions/run-tests-solidus-current
      - solidusio_extensions/run-tests-solidus-master
      - solidusio_extensions/store-test-results
    parameters:
      ruby_version:
        type: string
        default: '2.7'
  run-specs-with-postgres:
    executor:
      name: solidusio_extensions/postgres
      ruby_version: <<parameters.ruby_version>>
    steps:
      - checkout
      - solidusio_extensions/run-tests-solidus-older
      - solidusio_extensions/run-tests-solidus-current
      - solidusio_extensions/run-tests-solidus-master
      - solidusio_extensions/store-test-results
    parameters:
      ruby_version:
        type: string
        default: '3.0'
  run-specs-with-sqlite:
    executor:
      name: solidusio_extensions/sqlite
      ruby_version: <<parameters.ruby_version>>
    steps:
      - checkout
      - solidusio_extensions/run-tests-solidus-older
      - solidusio_extensions/run-tests-solidus-current
      - solidusio_extensions/run-tests-solidus-master
      - solidusio_extensions/store-test-results
    parameters:
      ruby_version:
        type: string
        default: '3.1'
  lint-code:
    executor: solidusio_extensions/sqlite-memory
    steps:
      - solidusio_extensions/lint-code

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - run-specs-with-mysql:
          ruby_version: '2.7'
          name: run-specs-with-mysql-ruby-2.7
      - run-specs-with-postgres:
          ruby_version: '3.0'
          name: run-specs-with-postgres-ruby-3.0
      - run-specs-with-sqlite:
          ruby_version: '3.1'
          name: run-specs-with-sqlite-ruby-3.1
      - lint-code

  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - run-specs-with-mysql:
          ruby_version: '2.7'
          name: run-specs-with-mysql-ruby-2.7
      - run-specs-with-postgres:
          ruby_version: '3.0'
          name: run-specs-with-postgres-ruby-3.0
      - run-specs-with-sqlite:
          ruby_version: '3.1'
          name: run-specs-with-sqlite-ruby-3.1
